[install]
colima = { pkg-path = "colima", systems = ["aarch64-darwin", "x86_64-darwin"] }
docker.pkg-path = "docker"
nodejs.pkg-path = "nodejs_20"

[vars]

[hook]

[options]
systems = ["x86_64-linux", "aarch64-darwin", "x86_64-darwin"]

