[install]
colima = { pkg-path = "colima", systems = ["aarch64-darwin", "x86_64-darwin"] }
docker.pkg-path = "docker"
nodejs.pkg-path = "nodejs_20"

[vars]

[hook]
script="""
# run docker deamon if not running
if [[ "$(uname | tr '[:upper:]' '[:lower:]')" = "darwin" ]]; then
  docker ps &>/dev/null || colima start
fi

if [[ "$(uname | tr '[:upper:]' '[:lower:]')" = "linux" ]]; then
  docker ps &>/dev/null || echo "Warning: docker daemon is not working. Run it with `sudo systemctl start docker`"
fi
"""

[options]
systems = ["x86_64-linux", "aarch64-darwin", "x86_64-darwin"]

