[install]
colima = { pkg-path = "colima", systems = ["aarch64-darwin", "x86_64-darwin"] }
docker.pkg-path = "docker"
nodejs.pkg-path = "nodejs_20"

[vars]

[hook]
script="""
if [[ "$(uname | tr '[:upper:]' '[:lower:]')" = "darwin" ]]; then
  docker ps &>/dev/null || echo '⚠️  Warning: cannot connect to docker daemon. You can run it with `colima start`. Remember to stop it before exiting environment!'
fi

if [[ "$(uname | tr '[:upper:]' '[:lower:]')" = "linux" ]]; then
  docker ps &>/dev/null || echo '⚠️  Warning: cannot connect to docker daemon. You can run it with `sudo systemctl start docker`. Remember to stop it before exiting environment!'
fi
"""

[options]
systems = ["x86_64-linux", "aarch64-darwin", "x86_64-darwin"]

